routes/web.php
<?php

    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login-form');
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::post('log-out', 'Auth\LoginController@logout')->name('logout');

    //Admin routes
    Route::namespace('Admin')
        ->name('admin.')
        ->prefix('admin')
        ->middleware(['auth', 'revalidate'])
        ->group(static function () {

            Route::resource('admins', 'AdminController');
            Route::get('inside', 'AdminController@inside')->name('inside.index');
            Route::resource('home-elements', 'AppHomeController');
            Route::post('home-elements/sort-f', 'AppHomeController@sortFirstRow')->name('home-screens.sort.f');
            Route::post('home-elements/sort-s', 'AppHomeController@sortSecondRow')->name('home-screens.sort.s');
            Route::resource('categories', 'CategoryController');
            Route::resource('consultation-forms', 'ConsultationFormController');
            Route::resource('consultation-titles', 'ConsultationTitleController');
            Route::resource('doctors', 'DoctorController');
            Route::resource('events', 'EventController');
            Route::resource('faqs', 'FaqController');
            Route::post('faqs/sort', 'FaqController@sort')->name('faqs.sort');
            Route::resource('hospitals', 'HospitalController');
            Route::resource('professions', 'ProfessionController');
            Route::resource('publishes', 'PublishController');
            Route::post('publishes/sort', 'PublishController@sort')->name('publishes.sort');
            Route::resource('recommendations', 'RecommendationController');
            Route::resource('social-life-categories', 'SocialLifeCategoryController');
            Route::post('social-life-categories/sort',
                'SocialLifeCategoryController@sort')->name('social-life-categories.sort');
            Route::resource('social-life-places', 'SocialLifePlaceController');
            Route::resource('static-contents', 'StaticContentController');
            Route::resource('users', 'UserController');
            Route::resource('video-categories', 'VideoCategoryController');
            Route::post('video-categories/sort', 'VideoCategoryController@sort')->name('video-categories.sort');
            Route::resource('videos', 'VideoController');
            Route::get('notification', 'NotificationController@index')->name('notification');
            Route::post('send-notification', 'NotificationController@send')->name('send-notification');

        });

    //Index route
    Route::get('/', static function () {
        return view('welcome');
    });

app/Models/Video.php
<?php

    /**
     * Created by Reliese Model.
     * Date: Sun, 16 Jun 2019 05:15:43 +0000.
     */

    namespace App\Models;

    use ChristianKuri\LaravelFavorite\Traits\Favoriteable;
    use Reliese\Database\Eloquent\Model as Eloquent;
    use Spatie\Searchable\Searchable;
    use Spatie\Searchable\SearchResult;

    /**
     * Class Video
     *
     * @property int            $id
     * @property int            $video_category_id
     * @property int            $consult_id
     * @property string         $title
     * @property string         $source
     * @property string         $content_path
     * @property string         $description
     * @property int            $has_consult
     * @property int            $status
     * @property \Carbon\Carbon $created_at
     * @property \Carbon\Carbon $updated_at
     *
     * @package App\Models
     */
    class Video extends Eloquent implements Searchable
    {

        use Favoriteable;

        protected $casts
            = [
                'video_category_id' => 'int',
                'consult_id'        => 'int',
                'has_consult'       => 'int',
                'status'            => 'int',
            ];

        protected $fillable
            = [
                'video_category_id',
                'consult_id',
                'title',
                'source',
                'content_path',
                'description',
                'has_consult',
                'status',
            ];

        public function category()
        {
            return $this->belongsTo(VideoCategory::class, 'video_category_id');
        }

        public function scopeByCategory($query, $category_id)
        {
            return $query->where('video_category_id', $category_id);
        }

        public function scopeActive($query)
        {
            return $query->where('status', 1);
        }

        public function getSearchResult(): SearchResult
        {
            return new SearchResult(
                $this,
                $this->title,
                $this->id
            );
        }
    }

app/Http/Controllers/Admin/VideoController.php
<?php

    namespace App\Http\Controllers\Admin;

    use App\Http\Controllers\Controller;
    use App\Http\Requests\VideoRequest;
    use App\Models\Video;
    use App\Models\VideoCategory;
    use Illuminate\Database\Eloquent\ModelNotFoundException;

    class VideoController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            if (\request('video_name')) {
                $rows = app(Video::class)
                    ->with('category')
                    ->where('title', 'LIKE', '%' . \request('video_name') . '%')
                    ->orderBy('title')
                    ->get();
            } else {
                $rows = app(Video::class)
                    ->with('category')
                    ->orderBy('title')
                    ->paginate(env('PAGER'));
            }

            return view('admin.videos.list', compact('rows'));
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            $categories = app(VideoCategory::class)
                ->active()
                ->orderBy('title')
                ->get(['id', 'title']);


            return view('admin.videos.create', compact('categories'));
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param \App\Http\Requests\VideoRequest $request
         *
         * @return void
         */
        public function store(VideoRequest $request)
        {
            $request->merge(['content_path' => 'videos/' . \Str::slug($request->title)]);

            app(Video::class)->create($request->all());

            return redirect()->route('admin.videos.index')->with('success', true);
        }

        /**
         * Display the specified resource.
         *
         * @param int $id
         *
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            //
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param int $id
         *
         * @return \Illuminate\Http\Response
         */
        public function edit($id)
        {
            try {

                $data = app(Video::class)->findOrFail($id);

            } catch (ModelNotFoundException $exception) {
                return redirect()->route('admin.videos.index');
            }

            $categories = app(VideoCategory::class)
                ->active()
                ->orderBy('title')
                ->get(['id', 'title']);

            return view('admin.videos.edit', compact('data', 'categories'));
        }

        /**
         * Update the specified resource in storage.
         *
         * @param \App\Http\Requests\VideoRequest $request
         * @param int                             $id
         *
         * @return void
         */
        public function update(VideoRequest $request, $id)
        {
            try {

                $data = app(Video::class)
                    ->findOrFail($id);

            } catch (ModelNotFoundException $exception) {
                return redirect()->route('admin.videos.index');
            }

            $request->merge(['content_path' => 'videos/' . \Str::slug($request->title)]);



            $data->update($request->all());

            return redirect()->route('admin.videos.index')->with('success', true);
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param int $id
         *
         * @return array|\Illuminate\Http\Response
         */
        public function destroy($id)
        {
            try {

                $data = app(Video::class)
                    ->findOrFail($id);

            } catch (ModelNotFoundException $exception) {
                return ['status' => false, 'message' => $exception->getMessage()];
            }

            $data->delete();

            session()->flash('success');

            return ['status' => true];
        }
    }

app/Http/Controllers/Api/VideoController.php
<?php

    namespace App\Http\Controllers\Api;

    use App\Http\Controllers\Controller;
    use App\Http\Resources\VideoResource;
    use App\Models\Video;
    use Illuminate\Database\Eloquent\ModelNotFoundException;

    class VideoController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
         */
        public function index()
        {
            $videos = app(Video::class)
                ->byCategory(\request('category_id'))
                ->active()
                ->get();


            return VideoResource::collection($videos);
        }


        /**
         * Display the specified resource.
         *
         * @param int $id
         *
         * @return \App\Http\Resources\VideoResource|array
         */
        public function show($id)
        {

            try {

                $video = app(Video::class)
                    ->with('consult')
                    ->active()
                    ->findOrFail($id);

            } catch (ModelNotFoundException $exception) {

                return ['status' => false, 'message' => $exception->getMessage()];

            }

            return new VideoResource($video);

        }

    }

resources/views/admin/videos/category-create.blade.php
@extends('layouts.app')

@section('page_extra_css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet"
          type="text/css"/>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Video Kategori
                        <small>Ekle</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form role="form" action="{{route('admin.video-categories.store')}}" method="post">
                        @csrf
                        <input type="hidden" name="order" value="1">
                        <div class="form-body">
                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="control-label">Başlık</label>
                                <input type="text" class="form-control input-lg" name="title" value="{{old('title')}}"/>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
                                <label class="control-label">Durum</label>
                                <select class="form-control input-lg" style="width: 25%" name="status">
                                    <option value="1" @if(old('status') === 1) selected @endif >Aktif</option>
                                    <option value="0" @if(old('status') === 0) selected @endif >Pasif</option>
                                </select>
                                @if ($errors->has('status'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/videos/category-edit.blade.php
@extends('layouts.app')

@section('page_extra_css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet"
          type="text/css"/>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Video Kategori
                        <small>Güncelle</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form role="form" action="{{route('admin.video-categories.update',['id'=>$data->id])}}" method="post">
                        @csrf
                        @method('PATCH')
                        <div class="form-body">
                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="control-label">Başlık</label>
                                <input type="text" class="form-control input-lg" name="title" value="{{old('title',$data->title)}}"/>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
                                <label class="control-label">Durum</label>
                                <select class="form-control input-lg" style="width: 25%" name="status">
                                    <<option value="1" @if(old('status', $data->status) === 1) selected @endif >Aktif
                                    </option>
                                    <option value="0" @if(old('status', $data->status) === 0) selected @endif >Pasif
                                    </option>
                                </select>
                                @if ($errors->has('status'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/videos/category-list.blade.php
@extends('layouts.app')
@section('page_extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/global/plugins/')}}" rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS -->
@endsection
@section('content')


    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="row">

        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Video Kategorileri
                        @if($rows instanceof \Illuminate\Pagination\LengthAwarePaginator)
                            ({{$rows->total()}})
                        @endif
                        <small>Liste</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="portlet box">
                <div class="portlet-body">
                    <div class="alert alert-info">
                        <strong>Bilgi!</strong> Sürükle bırak ile sıralamayı değiştirebilirsiniz.
                    </div>
                    <div class="table-scrollable">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th> Sıra</th>
                                <th> Başlık</th>
                                <th> Durum</th>
                                <th> İşlem</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($rows as $row)
                                <tr id="items-{{$row->id}}">
                                    <td class="align-middle"> {{$row->order}}</td>
                                    <td class="align-middle"> {{$row->title}}</td>
                                    <td>
                                        @if($row->status === 1)
                                            <span class="label label-sm label-success"> Aktif </span>
                                        @else
                                            <span class="label label-sm label-warning"> Pasif </span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{route('admin.video-categories.edit', ['id' => $row->id])}}"
                                           class="btn btn-xs btn-info">Güncelle</a>
                                        <a href="#"
                                           data-url="{{route('admin.video-categories.destroy', ['id' => $row->id])}}"
                                           class="btn btn-xs btn-danger">Sil</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    @if($rows instanceof \Illuminate\Pagination\LengthAwarePaginator)
                        <div class="row">
                            <div class="col-md-12">
                                {{ $rows->links() }}
                            </div>
                        </div>
                    @endif
                </div>
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- END PAGE BASE CONTENT -->
@endsection

@section('page_extra_js')
    @if(session('success'))
        @include('layouts.partial.toastr')
    @endif
    @include('layouts.partial.sweet-alert')
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $('tbody').sortable({
            update: function (event, ui) {
                let data = $(this).sortable('serialize');

                // POST to server using $.post or $.ajax
                $.ajax({
                    url: '{{route('admin.video-categories.sort')}}',
                    type: 'POST',
                    data: data,
                    success: function (result) {
                        if (result.status) {
                            location.reload();
                        }
                    }
                });
            }
        });
    </script>
@endsection

resources/views/admin/videos/create.blade.php
@extends('layouts.app')
@section('page_extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{asset('assets/global/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/global/plugins/select2/css/select2-bootstrap.min.css')}}" rel="stylesheet"
          type="text/css"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet"
          type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Video
                        <small>Ekle</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form role="form" action="{{route('admin.videos.store')}}" method="post">
                        @csrf
                        <div class="form-body">
                            <div class="form-group{{ $errors->has('video_category_id') ? ' has-error' : '' }}"
                                 style="width: 35%">
                                <label class="control-label">Kategori</label>
                                <select name="video_category_id" class="form-control input-lg select2">
                                    @foreach($categories as $category)
                                        <option @if(old('video_category_id') === $category->id) selected @endif value="{{$category->id}}">{{$category->title}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('video_category_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('video_category_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="control-label">Başlık</label>
                                <input type="text" class="form-control input-lg" name="title" value="{{old('title')}}"/>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('source') ? ' has-error' : '' }}">
                                <label class="control-label">Kaynak URL (Örn : https://vimeo.com/XXXXXXX)</label>
                                <input type="text" class="form-control input-lg" name="source" value="{{old('source')}}"/>
                                @if ($errors->has('source'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('source') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label class="control-label">İçerik</label>
                                <textarea id="summernote" name="description" class="form-control">{{old('description')}}</textarea>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
                                <label class="control-label">Durum</label>
                                <select class="form-control input-lg" style="width: 25%" name="status">
                                    <option value="1" @if(old('status') === 1) selected @endif >Aktif</option>
                                    <option value="0" @if(old('status') === 0) selected @endif >Pasif</option>
                                </select>
                                @if ($errors->has('status'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_extra_js')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="{{asset('assets/global/plugins/select2/js/select2.full.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/pages/scripts/components-select2.min.js')}}" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/lang/summernote-tr-TR.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#summernote').summernote(
                {
                    toolbar: [
                        ['style', ['style']],
                        ['font', ['bold', 'underline', 'clear']],
                        ['fontname', ['fontname']],
                        ['color', ['color']],
                        ['para', ['ul', 'ol', 'paragraph']],
                        ['table', ['table']],
                        ['insert', ['link', 'picture']],
                        ['view', ['fullscreen', 'codeview']],
                    ],
                    tabsize: 2,
                    height: 300,
                    lang: 'tr-TR'
                }
            );
        });
    </script>
    <!-- END PAGE LEVEL SCRIPTS -->

@endsection