routes/web.php
<?php

    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login-form');
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::post('log-out', 'Auth\LoginController@logout')->name('logout');

    //Admin routes
    Route::namespace('Admin')
        ->name('admin.')
        ->prefix('admin')
        ->middleware(['auth', 'revalidate'])
        ->group(static function () {

            Route::resource('admins', 'AdminController');
            Route::get('inside', 'AdminController@inside')->name('inside.index');
            Route::resource('home-elements', 'AppHomeController');
            Route::post('home-elements/sort-f', 'AppHomeController@sortFirstRow')->name('home-screens.sort.f');
            Route::post('home-elements/sort-s', 'AppHomeController@sortSecondRow')->name('home-screens.sort.s');
            Route::resource('categories', 'CategoryController');
            Route::resource('consultation-forms', 'ConsultationFormController');
            Route::resource('consultation-titles', 'ConsultationTitleController');
            Route::resource('doctors', 'DoctorController');
            Route::resource('events', 'EventController');
            Route::resource('faqs', 'FaqController');
            Route::post('faqs/sort', 'FaqController@sort')->name('faqs.sort');
            Route::resource('hospitals', 'HospitalController');
            Route::resource('professions', 'ProfessionController');
            Route::resource('publishes', 'PublishController');
            Route::post('publishes/sort', 'PublishController@sort')->name('publishes.sort');
            Route::resource('recommendations', 'RecommendationController');
            Route::resource('social-life-categories', 'SocialLifeCategoryController');
            Route::post('social-life-categories/sort',
                'SocialLifeCategoryController@sort')->name('social-life-categories.sort');
            Route::resource('social-life-places', 'SocialLifePlaceController');
            Route::resource('static-contents', 'StaticContentController');
            Route::resource('users', 'UserController');
            Route::resource('video-categories', 'VideoCategoryController');
            Route::post('video-categories/sort', 'VideoCategoryController@sort')->name('video-categories.sort');
            Route::resource('videos', 'VideoController');
            Route::get('notification', 'NotificationController@index')->name('notification');
            Route::post('send-notification', 'NotificationController@send')->name('send-notification');

        });

    //Index route
    Route::get('/', static function () {
        return view('welcome');
    });

resources/views/admin/social/category-create.blade.php
@extends('layouts.app')

@section('page_extra_css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet"
          type="text/css"/>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Sosyal Yaşam Kategori
                        <small>Ekle</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form role="form" action="{{route('admin.social-life-categories.store')}}" method="post"
                          enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="order" value="1">
                        <div class="form-body">
                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="control-label">Başlık</label>
                                <input type="text" class="form-control input-lg" name="title" value="{{old('title')}}"/>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('image_path') ? ' has-error' : '' }}">
                                <label class="control-label">Görsel</label>
                                <div class="input-group input-file" name="image_path" style="width: 50%">
                                    <input type="text" class="form-control" placeholder='Görsel dosyası seçiniz...'/>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default btn-choose" type="button">Seç</button>
                                    </span>
                                </div>
                                @if ($errors->has('image_path'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image_path') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('icon_path') ? ' has-error' : '' }}">
                                <label class="control-label">İkon</label>
                                <div class="input-group input-file" name="icon_path" style="width: 50%">
                                    <input type="text" class="form-control" placeholder='İkon dosyası seçiniz...'/>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default btn-choose" type="button">Seç</button>
                                    </span>

                                </div>
                                @if ($errors->has('icon_path'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('icon_path') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
                                <label class="control-label">Durum</label>
                                <select class="form-control input-lg" style="width: 25%" name="status">
                                    <option value="1" @if(old('status') === 1) selected @endif >Aktif</option>
                                    <option value="0" @if(old('status') === 0) selected @endif >Pasif</option>
                                </select>
                                @if ($errors->has('status'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_extra_js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/lang/summernote-tr-TR.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#summernote').summernote(
                {
                    toolbar: [
                        ['style', ['style']],
                        ['font', ['bold', 'underline', 'clear']],
                        ['fontname', ['fontname']],
                        ['color', ['color']],
                        ['para', ['ul', 'ol', 'paragraph']],
                        ['table', ['table']],
                        ['insert', ['link', 'picture']],
                        ['view', ['fullscreen', 'codeview']],
                    ],
                    tabsize: 2,
                    height: 300,
                    lang: 'tr-TR'
                }
            );

            bs_input_file();
        });

        function bs_input_file() {
            $(".input-file").before(
                function () {
                    if (!$(this).prev().hasClass('input-ghost')) {
                        let element = $("<input type='file' class='input-ghost' accept='image/jpeg,image/png,image/jpg' style='visibility:hidden; height:0'>");
                        element.attr("name", $(this).attr("name"));
                        element.change(function () {
                            element.next(element).find('input').val((element.val()).split('\\').pop());
                        });
                        $(this).find("button.btn-choose").click(function () {
                            element.click();
                        });
                        $(this).find("button.btn-reset").click(function () {
                            element.val(null);
                            $(this).parents(".input-file").find('input').val('');
                        });
                        $(this).find('input').css("cursor", "pointer");
                        $(this).find('input').mousedown(function () {
                            $(this).parents('.input-file').prev().click();
                            return false;
                        });
                        return element;
                    }
                }
            );
        }
    </script>
@endsection

resources/views/admin/social/category-edit.blade.php
@extends('layouts.app')

@section('page_extra_css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet"
          type="text/css"/>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Sosyal Yaşam Kategori
                        <small>Güncelle</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form role="form" action="{{route('admin.social-life-categories.update',['id'=>$data->id])}}"
                          method="post"
                          enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')
                        <input type="hidden" name="order" value="1">
                        <div class="form-body">
                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="control-label">Başlık</label>
                                <input type="text" class="form-control input-lg" name="title"
                                       value="{{old('title',$data->title)}}"/>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('image_path') ? ' has-error' : '' }}">
                                <label class="control-label">Görsel</label>
                                <input type="hidden" name="old_image_path" value="{{$data->image_path}}">
                                <div class="input-group input-file" name="image_path" style="width: 50%">
                                    <input type="text" class="form-control" placeholder='Dosya seçiniz...'/>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default btn-choose" type="button">Seç</button>
                                    </span>
                                    @if ($errors->has('image_path'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('image_path') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="row margin-top-15" style="margin-left: 0">
                                <img src="/storage/public/{{$data->image_path}}" alt="" style="width: 300px">
                            </div>
                            <div class="form-group{{ $errors->has('icon_path') ? ' has-error' : '' }}">
                                <label class="control-label">İkon</label>
                                <input type="hidden" name="old_icon_path" value="{{$data->icon_path}}">
                                <div class="input-group input-file" name="icon_path" style="width: 50%">
                                    <input type="text" class="form-control" placeholder='Dosya seçiniz...'/>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default btn-choose" type="button">Seç</button>
                                    </span>
                                    @if ($errors->has('icon_path'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('icon_path') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="row margin-top-15" style="margin-left: 0">
                                <img src="/storage/public/{{$data->icon_path}}" alt="" style="width: 300px">
                            </div>
                            <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
                                <label class="control-label">Durum</label>
                                <select class="form-control input-lg" style="width: 25%" name="status">
                                    <option value="1" @if(old('status', $data->status) === 1) selected @endif >Aktif
                                    </option>
                                    <option value="0" @if(old('status', $data->status) === 0) selected @endif >Pasif
                                    </option>
                                </select>
                                @if ($errors->has('status'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_extra_js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/lang/summernote-tr-TR.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#summernote').summernote(
                {
                    toolbar: [
                        ['style', ['style']],
                        ['font', ['bold', 'underline', 'clear']],
                        ['fontname', ['fontname']],
                        ['color', ['color']],
                        ['para', ['ul', 'ol', 'paragraph']],
                        ['table', ['table']],
                        ['insert', ['link', 'picture']],
                        ['view', ['fullscreen', 'codeview']],
                    ],
                    tabsize: 2,
                    height: 300,
                    lang: 'tr-TR'
                }
            );

            bs_input_file();
        });

        function bs_input_file() {
            $(".input-file").before(
                function () {
                    if (!$(this).prev().hasClass('input-ghost')) {
                        let element = $("<input type='file' class='input-ghost' accept='image/jpeg,image/png,image/jpg,image/svg' style='visibility:hidden; height:0'>");
                        element.attr("name", $(this).attr("name"));
                        element.change(function () {
                            element.next(element).find('input').val((element.val()).split('\\').pop());
                        });
                        $(this).find("button.btn-choose").click(function () {
                            element.click();
                        });
                        $(this).find("button.btn-reset").click(function () {
                            element.val(null);
                            $(this).parents(".input-file").find('input').val('');
                        });
                        $(this).find('input').css("cursor", "pointer");
                        $(this).find('input').mousedown(function () {
                            $(this).parents('.input-file').prev().click();
                            return false;
                        });
                        return element;
                    }
                }
            );
        }
    </script>
@endsection

resources/views/admin/social/category-list.blade.php
@extends('layouts.app')
@section('page_extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/global/plugins/')}}" rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS -->
@endsection
@section('content')


    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="row">

        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Sosyal Yaşam Kategori
                        @if($rows instanceof \Illuminate\Pagination\LengthAwarePaginator)
                            ({{$rows->total()}})
                        @endif
                        <small>Liste</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="portlet box">
                <div class="portlet-body">
                    <div class="alert alert-info">
                        <strong>Bilgi!</strong> Sürükle bırak ile sıralamayı değiştirebilirsiniz.
                    </div>
                    <div class="table-scrollable">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th> Sıra</th>
                                <th> Başlık</th>
                                <th> Durum</th>
                                <th> İşlem</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($rows as $row)
                                <tr id="items-{{$row->id}}">
                                    <td class="align-middle"> {{$row->order}}</td>
                                    <td class="align-middle"> {{$row->title}}</td>
                                    <td>
                                        @if($row->status === 1)
                                            <span class="label label-sm label-success"> Aktif </span>
                                        @else
                                            <span class="label label-sm label-warning"> Pasif </span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{route('admin.social-life-categories.edit', ['id' => $row->id])}}"
                                           class="btn btn-xs btn-info">Güncelle</a>
                                        <a href="#"
                                           data-url="{{route('admin.social-life-categories.destroy', ['id' => $row->id])}}"
                                           class="btn btn-xs btn-danger">Sil</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    @if($rows instanceof \Illuminate\Pagination\LengthAwarePaginator)
                        <div class="row">
                            <div class="col-md-12">
                                {{ $rows->links() }}
                            </div>
                        </div>
                    @endif
                </div>
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- END PAGE BASE CONTENT -->
@endsection

@section('page_extra_js')
    @if(session('success'))
        @include('layouts.partial.toastr')
    @endif
    @include('layouts.partial.sweet-alert')
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $('tbody').sortable({
            update: function (event, ui) {
                let data = $(this).sortable('serialize');

                // POST to server using $.post or $.ajax
                $.ajax({
                    url: '{{route('admin.social-life-categories.sort')}}',
                    type: 'POST',
                    data: data,
                    success: function (result) {
                        if (result.status) {
                            location.reload();
                        }
                    }
                });
            }
        });
    </script>
@endsection

resources/views/admin/social/list.blade.php
@extends('layouts.app')

@section('page_extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS -->
@endsection

@section('content')


    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="row">

        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Sosyal Yaşam Mekanlar
                        @if($rows instanceof \Illuminate\Pagination\LengthAwarePaginator)
                            ({{$rows->total()}})
                        @endif
                        <small>Liste</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="portlet box">
                <div class="portlet-body">
                    <form role="form" action="{{route('admin.social-life-places.index')}}">
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" name="place_name" class="form-control"
                                       placeholder="Mekan başlığına göre...">
                                <span class="input-group-btn">
                                   <button class="btn green" type="submit">ARA</button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </div>
                    </form>
                    <div class="table-scrollable">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th> Kategori</th>
                                <th> Başlık</th>
                                <th> Durum</th>
                                <th> İşlem</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($rows as $row)
                                <tr>
                                    <td> {{$row->category->title}}</td>
                                    <td> {{$row->name}}</td>
                                    <td>
                                        @if($row->status === 1)
                                            <span class="label label-sm label-success"> Aktif </span>
                                        @else
                                            <span class="label label-sm label-warning"> Pasif </span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{route('admin.social-life-places.edit', ['id' => $row->id])}}"
                                           class="btn btn-xs btn-info">Güncelle</a>
                                        <a href="#"
                                           data-url="{{route('admin.social-life-places.destroy', ['id' => $row->id])}}"
                                           class="btn btn-xs btn-danger">Sil</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                    </div>
                    @if($rows instanceof \Illuminate\Pagination\LengthAwarePaginator)
                        <div class="row">
                            <div class="col-md-12">
                                {{ $rows->links() }}
                            </div>
                        </div>
                    @endif
                </div>
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- END PAGE BASE CONTENT -->
@endsection

@section('page_extra_js')
    @if(session('success'))
        @include('layouts.partial.toastr')
    @endif
    @include('layouts.partial.sweet-alert')
@endsection