routes/web.php
<?php

    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login-form');
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::post('log-out', 'Auth\LoginController@logout')->name('logout');

    //Admin routes
    Route::namespace('Admin')
        ->name('admin.')
        ->prefix('admin')
        ->middleware(['auth', 'revalidate'])
        ->group(static function () {

            Route::resource('admins', 'AdminController');
            Route::get('inside', 'AdminController@inside')->name('inside.index');
            Route::resource('home-elements', 'AppHomeController');
            Route::post('home-elements/sort-f', 'AppHomeController@sortFirstRow')->name('home-screens.sort.f');
            Route::post('home-elements/sort-s', 'AppHomeController@sortSecondRow')->name('home-screens.sort.s');
            Route::resource('categories', 'CategoryController');
            Route::resource('consultation-forms', 'ConsultationFormController');
            Route::resource('consultation-titles', 'ConsultationTitleController');
            Route::resource('doctors', 'DoctorController');
            Route::resource('events', 'EventController');
            Route::resource('faqs', 'FaqController');
            Route::post('faqs/sort', 'FaqController@sort')->name('faqs.sort');
            Route::resource('hospitals', 'HospitalController');
            Route::resource('professions', 'ProfessionController');
            Route::resource('publishes', 'PublishController');
            Route::post('publishes/sort', 'PublishController@sort')->name('publishes.sort');
            Route::resource('recommendations', 'RecommendationController');
            Route::resource('social-life-categories', 'SocialLifeCategoryController');
            Route::post('social-life-categories/sort',
                'SocialLifeCategoryController@sort')->name('social-life-categories.sort');
            Route::resource('social-life-places', 'SocialLifePlaceController');
            Route::resource('static-contents', 'StaticContentController');
            Route::resource('users', 'UserController');
            Route::resource('video-categories', 'VideoCategoryController');
            Route::post('video-categories/sort', 'VideoCategoryController@sort')->name('video-categories.sort');
            Route::resource('videos', 'VideoController');
            Route::get('notification', 'NotificationController@index')->name('notification');
            Route::post('send-notification', 'NotificationController@send')->name('send-notification');

        });

    //Index route
    Route::get('/', static function () {
        return view('welcome');
    });

app/Models/User.php
<?php

    /**
     * Created by Reliese Model.
     * Date: Sun, 12 May 2019 08:25:25 +0000.
     */

    namespace App\Models;

    /**
     * Class User
     *
     * @property int            $id
     * @property string         $identifier
     * @property int            $type
     * @property string         $user_name
     * @property \Carbon\Carbon $birthday
     * @property string         $email
     * @property string         $city
     * @property string         $country
     * @property string         $hear_us
     * @property int            $is_kvk_accepted
     * @property \Carbon\Carbon $email_verified_at
     * @property string         $password
     * @property string         $remember_token
     * @property \Carbon\Carbon $created_at
     * @property \Carbon\Carbon $updated_at
     *
     * @package App\Models
     */

    use App\Enums\UserType;
    use Carbon\Carbon;
    use ChristianKuri\LaravelFavorite\Traits\Favoriteability;
    use Illuminate\Foundation\Auth\User as Authenticatable;
    use Illuminate\Notifications\Notifiable;
    use Laravel\Passport\HasApiTokens;
    use Spatie\Permission\Traits\HasRoles;

    class User extends Authenticatable
    {
        use HasApiTokens, Notifiable, HasRoles, Favoriteability;

        protected $casts
            = [
                'type'            => 'int',
                'is_kvk_accepted' => 'int',
            ];

        protected $dates
            = [
                'birthday',
                'email_verified_at',
            ];

        protected $hidden
            = [
                'password',
                'remember_token',
            ];

        protected $fillable
            = [
                'identifier',
                'type',
                'user_name',
                'birthday',
                'email',
                'city',
                'country',
                'hear_us',
                'is_kvk_accepted',
                'email_verified_at',
                'password',
                'remember_token',
            ];

        public function setBirthdayAttribute($value)
        {
            $this->attributes['birthday'] = Carbon::createFromFormat('d-m-Y', $value);
        }


        public function findForPassport($username)
        {
            return $this->where('user_name', $username)->first();
        }


        public function recommendations()
        {
            return $this->hasMany(Recommendation::class);
        }

        public function reminders()
        {
            return $this->hasMany(Reminder::class);
        }

        public function notifications()
        {
            return $this->hasMany(Notification::class);
        }

        public function scopeAdmins($query)
        {
            return $query->where('type', UserType::ADMIN);
        }

        public function scopeApplicationUsers($query)
        {
            return $query->where('type', UserType::APPUSER);
        }

    }

app/Http/Controllers/Admin/UserController.php
<?php

    namespace App\Http\Controllers\Admin;

    use App\Enums\UserType;
    use App\Http\Controllers\Controller;
    use Illuminate\Foundation\Auth\User;
    use Illuminate\Http\Request;

    class UserController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            if (\request('user_name')) {
                $rows = app(User::class)
                    ->where('type', UserType::APPUSER)
                    ->where('user_name', 'LIKE', '%' . \request('user_name') . '%')
                    ->orderBy('user_name')
                    ->get();
            } else {
                $rows = app(User::class)
                    ->where('type', UserType::APPUSER)
                    ->where('user_name', 'LIKE', '%' . \request('user_name') . '%')
                    ->orderBy('user_name')
                    ->paginate(env('PAGER'));
            }

            return view('admin.users.list', compact('rows'));
        }


        /**
         * Display the specified resource.
         *
         * @param int $id
         *
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            //
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param int $id
         *
         * @return \Illuminate\Http\Response
         */
        public function edit($id)
        {
            //
        }

        /**
         * Update the specified resource in storage.
         *
         * @param \Illuminate\Http\Request $request
         * @param int                      $id
         *
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, $id)
        {
            //
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param int $id
         *
         * @return \Illuminate\Http\Response
         */
        public function destroy($id)
        {
            //
        }
    }

app/Http/Controllers/Api/UserController.php
<?php

    namespace App\Http\Controllers\Api;

    use App\Http\Controllers\Controller;
    use App\Http\Requests\UserUpdateRequest;
    use App\Http\Resources\UserResource;

    class UserController extends Controller
    {

        /**
         * Display the specified resource.
         *
         * @param int $id
         *
         * @return \App\Http\Controllers\Api\UserResource|\App\Http\Resources\UserResource|\Illuminate\Http\Response
         */
        public function show($id)
        {
            $user = auth()->user();

            return new UserResource($user);
        }


        /**
         * Update the specified resource in storage.
         *
         * @param \App\Http\Requests\UserUpdateRequest $request
         * @param int                                  $id
         *
         * @return array
         */
        public function update(UserUpdateRequest $request, $id)
        {
            $user = auth()->user();

            if (!$user) {
                return ['status' => false, 'message' => 'Kullanıcı bulunamadı!'];
            }

            $user->user_name = $request->user_name;
            $user->password  = \Hash::make($request->password);
            $user->password_reset = 0;
            $user->save();

            return ['status' => true];

        }

        /**
         * Remove the specified resource from storage.
         *
         * @param int $id
         *
         * @return \Illuminate\Http\Response
         */
        public function destroy($id)
        {
            //todo : neler olacak?
        }
    }

resources/views/admin/users/create.blade.php
@extends('layouts.app')
@section('page_extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{asset('assets/global/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/global/plugins/select2/css/select2-bootstrap.min.css')}}" rel="stylesheet"
          type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Hastane
                        <small>Ekle</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form role="form" action="{{route('admin.hospitals.store')}}" method="post">
                        @csrf
                        <div class="form-body">
                            <div class="form-group{{ $errors->has('city_id') ? ' has-error' : '' }}">
                                <label class="control-label">Şehir</label>
                                <select id="single" name="city_id" class="form-control input-lg select2">
                                    @foreach($cities as $city)
                                        <option @if(old('city_id') === $city->id) selected @endif value="{{$city->id}}">{{$city->name}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('city_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('city_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="control-label">Hastane Adı</label>
                                <input type="text" class="form-control input-lg" name="title" value="{{old('title')}}"/>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('sub_title') ? ' has-error' : '' }}">
                                <label class="control-label">Alt Başlık</label>
                                <input type="text" class="form-control input-lg" name="sub_title" value="{{old('sub_title')}}"/>
                                @if ($errors->has('sub_title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('sub_title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                                <label class="control-label">Adres</label>
                                <input type="text" class="form-control input-lg" name="address" value="{{old('address')}}"/>
                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('location') ? ' has-error' : '' }}">
                                <label class="control-label">Lokasyon (Koordinatları arada virgül ile yazınız. Örn :
                                    41.1212,29.1212)</label>
                                <input type="text" class="form-control input-lg" style="width: 50%" value="{{old('location')}}"
                                       name="location"/>
                                @if ($errors->has('location'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('location') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                                <label class="control-label">Durum</label>
                                <select name="status" class="form-control input-lg" style="width: 25%">
                                    <option value="1" @if(old('status') === 1) selected @endif >Aktif</option>
                                    <option value="0" @if(old('status') === 0) selected @endif >Pasif</option>
                                </select>
                                @if ($errors->has('status'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_extra_js')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="{{asset('assets/global/plugins/select2/js/select2.full.min.js')}}" type="text/javascript"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{{asset('assets/pages/scripts/components-select2.min.js')}}" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')
@section('page_extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{asset('assets/global/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/global/plugins/select2/css/select2-bootstrap.min.css')}}" rel="stylesheet"
          type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Hastane
                        <small>Güncelle</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form role="form" action="{{route('admin.hospitals.update',['id'=>$data->id])}}" method="post">
                        @csrf
                        @method('PATCH')
                        <div class="form-body">
                            <div class="form-group{{ $errors->has('city_id') ? ' has-error' : '' }}">
                                <label class="control-label">Şehir</label>
                                <select id="single" name="city_id" class="form-control input-lg select2">
                                    @foreach($cities as $city)
                                        <option @if(old('city_id', $data->city_id) === $city->id) selected
                                                @endif value="{{$city->id}}">{{$city->name}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('city_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('city_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label class="control-label">Hastane Adı</label>
                                <input type="text" class="form-control input-lg" name="title"
                                       value="{{old('title',$data->title)}}"/>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('sub_title') ? ' has-error' : '' }}">
                                <label class="control-label">Alt Başlık</label>
                                <input type="text" class="form-control input-lg" name="sub_title"
                                       value="{{old('sub_title', $data->sub_title)}}"/>
                                @if ($errors->has('sub_title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('sub_title') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                                <label class="control-label">Adres</label>
                                <input type="text" class="form-control input-lg" name="address"
                                       value="{{old('address', $data->address)}}"/>
                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('location') ? ' has-error' : '' }}">
                                <label class="control-label">Lokasyon (Koordinatları arada virgül ile yazınız. Örn :
                                    41.1212,29.1212)</label>
                                <input type="text" class="form-control input-lg" style="width: 50%"
                                       value="{{old('location', $data->location)}}"
                                       name="location"/>
                                @if ($errors->has('location'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('location') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                                <label class="control-label">Durum</label>
                                <select name="status" class="form-control input-lg" style="width: 25%">
                                    <option value="1" @if(old('status', $data->status) === 1) selected @endif >Aktif
                                    </option>
                                    <option value="0" @if(old('status', $data->status) === 0) selected @endif >Pasif
                                    </option>
                                </select>
                                @if ($errors->has('status'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_extra_js')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="{{asset('assets/global/plugins/select2/js/select2.full.min.js')}}" type="text/javascript"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{{asset('assets/pages/scripts/components-select2.min.js')}}" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
@endsection

resources/views/admin/users/list.blade.php
@extends('layouts.app')

@section('page_extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS -->
@endsection

@section('content')


    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="row">

        <div class="col-md-12">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <div class="page-title">
                    <h1>Uygulama Kullanıcıları
                        @if($rows instanceof \Illuminate\Pagination\LengthAwarePaginator)
                            ({{$rows->total()}})
                        @endif
                        <small>Liste</small>
                    </h1>
                </div>
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="portlet box">
                <div class="portlet-body">
                    <form role="form" action="{{route('admin.hospitals.index')}}">
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" name="user_name" class="form-control"
                                       placeholder="Kullanıcı adına göre...">
                                <span class="input-group-btn">
                                   <button class="btn green" type="submit">ARA</button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </div>
                    </form>
                    <div class="table-scrollable">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th> Kullanıcı Adı</th>
                                <th> Email</th>
                                <th> Şehir</th>
                                <th> Doğum Tarihi</th>
                                <!--<th> İşlem</th>-->
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($rows as $row)
                                <tr>
                                    <td> {{$row->user_name}}</td>
                                    <td> {{$row->email}}</td>
                                    <td> {{$row->city}}</td>
                                    <td> {{Carbon\Carbon::parse($row->birthday)->format('d-m-Y')}}</td>

                                <!--<td>
                                        <a href="{{route('admin.users.edit', ['id' => $row->id])}}"
                                           class="btn btn-xs btn-info">Güncelle</a>
                                        <a href="#"
                                           data-url="{{route('admin.users.destroy', ['id' => $row->id])}}"
                                           class="btn btn-xs btn-danger">Sil</a>
                                    </td>-->
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                    </div>
                    @if($rows instanceof \Illuminate\Pagination\LengthAwarePaginator)
                        <div class="row">
                            <div class="col-md-12">
                                {{ $rows->links() }}
                            </div>
                        </div>
                    @endif
                </div>
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- END PAGE BASE CONTENT -->
@endsection

{{--
@section('page_extra_js')
    @if(session('success'))
        @include('layouts.partial.toastr')
    @endif
    @include('layouts.partial.sweet-alert')
@endsection
--}}